#!/usr/bin/zsh

lrun(){
    userhost=$1
    user=$(echo $userhost | cut -d@ -f1)
    if [ "x$user" = "x" ]; then
        user=ubuntu
    fi
    host=$(echo $userhost | cut -d@ -f2)
    shift
    lxc exec $host -- sudo --login --user $user $@
}

lsh(){
    lrun $@
}

v2gif () {
    for MP4 in "$@"; do
        pvar MP4
        NAME="$(echo "$MP4" | rev | cut -d"." -f2- | rev)"
        pvar NAME
        ffmpeg -i "$MP4" -r 10 -f image2pipe -vcodec ppm | \
            convert -delay 5 -loop 0 - "${NAME}.gif"
    done
}

vmdisk() {
    HDDIR=${HOME}/vm
    HD=$1
    SIZE=$2
    qemu-virgil.qemu-img create -f qcow2 ${HDDIR}/${HD}.img ${SIZE}
}

vminst() {
    VM=$1
    ISO=$2
    HDDIR=${HOME}/vm
    ISODIR=${HOME}/isos
    qemu-virgil \
        -enable-kvm \
        -m 4096 \
        -device virtio-vga,virgl=on \
        -display sdl,gl=on \
        -netdev user,id=net.0,hostfwd=tcp::10022-:22 \
        -device virtio-net-pci,netdev=net.0 \
        -cdrom ${ISO} \
        -boot once=d \
        -drive file=${HDDIR}/${VM}.img,if=virtio
}

vmrun() {
    VM=$1
    HDDIR=${HOME}/vm
    qemu-virgil \
        -enable-kvm \
        -m 4096 \
        -device virtio-vga,virgl=on \
        -display sdl,gl=on \
        -netdev user,id=net.0,hostfwd=tcp::10022-:22 \
        -device virtio-net-pci,netdev=net.0 \
        -drive file=${HDDIR}/${VM}.img,if=virtio
}
